Repository pimcore/static-resolver-bundle, pull requests merged in 2024-06, with the labels that each got.

#41 Added php 8.3 support
  .github/workflows/codeception.yaml
  .github/workflows/qodana.yaml
  composer.json
Labels: Task

#42 Add Folder resolver getById.
  src/Models/User/FolderResolver.php
  src/Models/User/FolderResolverInterface.php
Labels: Improvement

#44 Add create Folder method.
  src/Models/User/FolderResolver.php
  src/Models/User/FolderResolverInterface.php
Labels: Improvement

#45 Add config resolver
  src/Lib/ConfigResolver.php
  src/Lib/ConfigResolverInterface.php
Labels: Task

#46 Add Lib Document Resolver
  src/Lib/DocumentResolver.php
  src/Lib/DocumentResolverInterface.php
Labels: Task

#48 Fix document resolver interface
  src/Lib/DocumentResolver.php
  src/Lib/DocumentResolverInterface.php
Labels: Task

#49 Add Admin Tool reorderWebsiteLanguages.
  src/Lib/Tools/AdminResolver.php
  src/Lib/Tools/AdminResolverInterface.php
Labels: New Feature

#50 [Task] Add Image Thumbnail Resolver
  src/Models/Asset/Image/Thumbnail/ConfigResolver.php
  src/Models/Asset/Image/Thumbnail/ConfigResolverInterface.php
Labels: Task

#51 Add Models DataObject FolderResolver
  src/Models/DataObject/DataObjectFolderResolver.php
  src/Models/DataObject/DataObjectFolderResolverInterface.php
  src/Models/Element/ServiceResolver.php
  src/Models/Element/ServiceResolverInterface.php
Labels: Task
