Repository pimcore/static-resolver-bundle, pull requests merged in 2024-11, with the labels that each got.

#68 [Task] Add languages to tool/admin
  src/Lib/Tools/AdminResolver.php
  src/Lib/Tools/AdminResolverInterface.php
Labels: Pimcore:ToDo, Task

#69 Add getObjectsReferencingUser to Resolver
  src/Models/DataObject/DataObjectServiceResolver.php
  src/Models/DataObject/DataObjectServiceResolverInterface.php
Labels: Improvement

#72 [Task] Add resolver for GroupConfig and DefinitionCache
  src/Models/DataObject/ClassificationStore/DefinitionCacheResolverInterface.php
  src/Models/DataObject/ClassificationStore/DefinitionCacheResolverResolver.php
  src/Models/DataObject/ClassificationStore/GroupConfigResolver.php
  src/Models/DataObject/ClassificationStore/GroupConfigResolverInterface.php
Labels: Task

#71 [Task] Add caution section
  README.md
Labels: Pimcore:ToDo, Task

#76 Add deprecation.
  src/Db/DbResolver.php
  src/Db/DbResolverInterface.php
  src/Lib/Cache/RuntimeCacheResolver.php
  src/Lib/Cache/RuntimeCacheResolverInterface.php
  src/Lib/CacheResolver.php
  src/Lib/ToolResolver.php
  src/Lib/ToolResolverInterface.php
  src/Lib/Tools/Authentication/AuthenticationResolver.php
  src/Lib/Tools/Authentication/AuthenticationResolverInterface.php
  src/Models/Asset/AssetResolverInterface.php
  src/Models/Asset/AssetServiceResolverInterface.php
  src/Models/DataObject/ClassDefinitionResolver.php
  src/Models/DataObject/ClassDefinitionResolverInterface.php
  src/Models/DataObject/ClassificationStore/ServiceResolverInterface.php
  src/Models/DataObject/ConcreteObjectResolver.php
  src/Models/DataObject/ConcreteObjectResolverInterface.php
  src/Models/DataObject/DataObjectResolverInterface.php
  src/Models/DataObject/DataObjectServiceResolverInterface.php
  src/Models/DataObject/FieldCollection/DefinitionResolverInterface.php
  src/Models/DataObject/Objectbrick/DefinitionResolver.php
  src/Models/DataObject/Objectbrick/DefinitionResolverInterface.php
  src/Models/DataObject/QuantityValue/UnitResolverInterface.php
  src/Models/Document/DocumentResolverInterface.php
  src/Models/Document/DocumentServiceResolverInterface.php
  src/Models/Element/ServiceResolver.php
  src/Models/Element/ServiceResolverInterface.php
  src/Models/Schedule/TaskResolver.php
  src/Models/Schedule/TaskResolverInterface.php
  src/Models/Tool/SettingsStoreResolverInterface.php
  src/Models/Tool/TmpStoreResolver.php
  src/Models/Tool/TmpStoreResolverInterface.php
  src/Models/User/Permission/DefinitionResolverInterface.php
  src/Models/User/UserResolver.php
  src/Models/User/UserResolverInterface.php
  src/Models/Version/VersionResolver.php
  src/Models/Version/VersionResolverInterface.php
Labels: Bug
