Repository pimcore/static-resolver-bundle, pull requests merged in 2025-04, with the labels that each got.

#102 [Task] Introducing user parameter to make async work in studio
  src/Models/DataObject/DataObjectServiceResolver.php
  src/Models/DataObject/DataObjectServiceResolverInterface.php
Labels: Pimcore:ToDo, Task

#103 [Task] Add missing methods to ClassificationStore Service
  src/Models/DataObject/ClassificationStore/ServiceResolver.php
  src/Models/DataObject/ClassificationStore/ServiceResolverInterface.php
Labels: Task

#104 Removed unnecessary return type EncryptedField
  src/Models/DataObject/ClassDefinitionServiceResolver.php
  src/Models/DataObject/ClassDefinitionServiceResolverInterface.php
  src/Models/DataObject/ClassificationStore/ServiceResolver.php
  src/Models/DataObject/ClassificationStore/ServiceResolverInterface.php
Labels: Improvement

#105 Add Product Registration
  .github/ci/files/config/packages/test/config.yaml
Labels: Task

#106 Fix codeception
  .github/workflows/codeception.yaml
Labels: Task
